wandb_version: 1

lr_discriminator:
  desc: null
  value: 0.003671007736739079
lr_generator:
  desc: null
  value: 0.0029833354466700717
sampling_iterations:
  desc: null
  value: 5
training_iterations:
  desc: null
  value: 45
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689058533.088581
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
