wandb_version: 1

alpha:
  desc: null
  value: 0.6
batch_size:
  desc: null
  value: 0.09938516049307151
epochs:
  desc: null
  value: 100
feature_dim:
  desc: null
  value: 8
gamma:
  desc: null
  value: 0.6028599335791377
lam:
  desc: null
  value: 900
lr:
  desc: null
  value: 0.003696555114847906
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689771791.223781
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
