wandb_version: 1

alpha:
  value: 0.1
batch_size_ratio:
  value: 0.1
beta_adj:
  value: 10
beta_x:
  value: 10
disable_u:
  value: false
dropout:
  value: 0.01
encoder_type:
  value: gcn
epochs:
  value: 10
feature_dim:
  value: 2
graph_pool_type:
  value: mean
h_dim:
  value: 16
lambda_cfe:
  value: 1
lambda_kl:
  value: 1
lambda_sim:
  value: 1
lr:
  value: 0.001
weight_decay:
  value: 4.0e-05
z_dim:
  value: 16
