wandb_version: 1

alpha:
  desc: null
  value: 0.7000000000000001
batch_size:
  desc: null
  value: 0.08085429484991995
epochs:
  desc: null
  value: 20
feature_dim:
  desc: null
  value: 8
gamma:
  desc: null
  value: 0.2736081838177662
lam:
  desc: null
  value: 250
lr:
  desc: null
  value: 0.003709913076663742
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689771737.46405
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
