wandb_version: 1

alpha:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
feature_dim:
  desc: null
  value: 8
gamma:
  desc: null
  value: 0.1
lam:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.002
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689859522.401419
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
