wandb_version: 1

alpha:
  desc: null
  value: 0.8999999999999999
batch_size:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 50
gamma:
  desc: null
  value: 0.5
lam:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690213565.528879
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
