wandb_version: 1

alpha:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 0.051761100381802934
epochs:
  desc: null
  value: 80
feature_dim:
  desc: null
  value: 8
gamma:
  desc: null
  value: 0.27728990894230643
lam:
  desc: null
  value: 450
lr:
  desc: null
  value: 0.0060771750087171145
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689771916.503474
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 23
      - 37
      4: 3.7.13
      5: 0.15.5
      8:
      - 5
